"""
Dynamic Tool Runtime - Core runtime for executing and managing dynamic tools.
Allows LLM to generate Python functions that are safely validated and executed.
"""
import logging
import uuid
from typing import Dict, Any, Callable, Optional, List
from datetime import datetime
from pathlib import Path

from .tool_validator import DynamicToolValidator

logger = logging.getLogger(__name__)


def get_dynamo_service():
    """Lazy import to avoid circular dependencies"""
    try:
        # Use relative import to work regardless of how module is loaded
        from ..services.dynamo_service import get_dynamo_service as _get_dynamo_service
        return _get_dynamo_service()
    except Exception as e:
        logger.warning(f"⚠️ DynamoDB service not available: {e}")
        return None


class DynamicToolRuntime:
    """
    Runtime environment for dynamic tools generated by LLM.

    Features:
    - Validates and compiles LLM-generated Python code
    - Stores tools in memory and on disk
    - Provides execution sandbox
    - Tracks tool metadata and usage stats
    - Supports tool versioning and updates
    """

    def __init__(self, storage_dir: Optional[str] = None):
        self.validator = DynamicToolValidator()
        self.tools: Dict[str, Dict[str, Any]] = {}  # tool_name -> metadata
        self.tool_functions: Dict[str, Callable] = {}  # tool_name -> callable
        self.storage_dir = Path(storage_dir) if storage_dir else Path(__file__).parent / "stored_tools"
        self.storage_dir.mkdir(parents=True, exist_ok=True)

    def register_tool(
        self,
        tool_name: str,
        code: str,
        description: Optional[str] = None,
        category: Optional[str] = None,
        created_by: str = "llm",
    ) -> Dict[str, Any]:
        """
        Register a new dynamic tool from LLM-generated code.

        Args:
            tool_name: Unique name for the tool
            code: Python source code string
            description: Optional description of what the tool does
            category: Optional category (e.g., "plumbing", "diagnosis")
            created_by: Who created this tool (default: "llm")

        Returns:
            dict with registration result (success, tool_id, errors)
        """
        logger.info(f"🔧 Registering dynamic tool: {tool_name}")

        # Step 1: Validate code
        validation_result = self.validator.validate(code, tool_name)

        if not validation_result["valid"]:
            logger.error(f"❌ Tool validation failed: {validation_result['errors']}")
            return {
                "success": False,
                "errors": validation_result["errors"],
                "tool_name": tool_name,
            }

        # Step 2: Extract metadata
        function_def = validation_result["function_def"]
        metadata = self.validator.extract_function_metadata(function_def)

        # Step 3: Compile and execute code to create callable
        try:
            namespace = {}
            exec(code, namespace)
            tool_function = namespace.get(tool_name)

            if not callable(tool_function):
                return {
                    "success": False,
                    "errors": [f"Function {tool_name} is not callable"],
                    "tool_name": tool_name,
                }

        except Exception as e:
            logger.error(f"❌ Failed to compile tool: {e}", exc_info=True)
            return {
                "success": False,
                "errors": [f"Compilation error: {str(e)}"],
                "tool_name": tool_name,
            }

        # Step 4: Generate unique tool ID
        tool_id = f"dt_{uuid.uuid4().hex[:12]}"

        # Step 5: Store tool metadata
        tool_record = {
            "tool_id": tool_id,
            "tool_name": tool_name,
            "code": code,
            "description": description or metadata.get("docstring", "No description"),
            "category": category or "general",
            "created_by": created_by,
            "created_at": datetime.utcnow().isoformat(),
            "metadata": metadata,
            "usage_count": 0,
            "last_used_at": None,
            "version": 1,
        }

        self.tools[tool_name] = tool_record
        self.tool_functions[tool_name] = tool_function

        # Step 6: Persist to disk
        self._save_tool_to_disk(tool_name, tool_record)

        # Step 7: Persist to DynamoDB (for Custom AI Diagnostic Models)
        self._save_tool_to_dynamodb(tool_record)

        logger.info(f"✅ Tool registered successfully: {tool_name} ({tool_id})")

        return {
            "success": True,
            "tool_id": tool_id,
            "tool_name": tool_name,
            "metadata": metadata,
            "description": tool_record["description"],
        }

    def execute_tool(
        self,
        tool_name: str,
        arguments: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Execute a registered dynamic tool.

        Args:
            tool_name: Name of the tool to execute
            arguments: Arguments to pass to the tool function

        Returns:
            dict with execution result (success, result, error)
        """
        if tool_name not in self.tool_functions:
            return {
                "success": False,
                "error": f"Tool '{tool_name}' not found",
                "available_tools": list(self.tools.keys()),
            }

        tool_function = self.tool_functions[tool_name]

        try:
            # Execute the tool
            result = tool_function(**arguments)

            # Update usage stats in memory
            self.tools[tool_name]["usage_count"] += 1
            self.tools[tool_name]["last_used_at"] = datetime.utcnow().isoformat()

            # Update usage stats in DynamoDB
            tool_id = self.tools[tool_name].get("tool_id")
            if tool_id:
                self._update_tool_usage_in_dynamodb(tool_id)

            logger.info(f"✅ Tool executed successfully: {tool_name}")

            return {
                "success": True,
                "result": result,
                "tool_name": tool_name,
            }

        except Exception as e:
            logger.error(f"❌ Tool execution error: {e}", exc_info=True)
            return {
                "success": False,
                "error": str(e),
                "tool_name": tool_name,
            }

    def list_tools(self, category: Optional[str] = None) -> List[Dict[str, Any]]:
        """List all registered tools, optionally filtered by category"""
        tools = list(self.tools.values())

        if category:
            tools = [t for t in tools if t.get("category") == category]

        return tools

    def get_tool_info(self, tool_name: str) -> Optional[Dict[str, Any]]:
        """Get metadata for a specific tool"""
        return self.tools.get(tool_name)

    def delete_tool(self, tool_name: str) -> bool:
        """Delete a tool from registry"""
        if tool_name in self.tools:
            del self.tools[tool_name]
            del self.tool_functions[tool_name]

            # Remove from disk
            tool_file = self.storage_dir / f"{tool_name}.py"
            if tool_file.exists():
                tool_file.unlink()

            logger.info(f"🗑️ Tool deleted: {tool_name}")
            return True

        return False

    def _save_tool_to_disk(self, tool_name: str, tool_record: Dict[str, Any]):
        """Save tool to disk for persistence"""
        try:
            tool_file = self.storage_dir / f"{tool_name}.py"

            # Write code with metadata header
            content = f'''"""
Dynamic Tool: {tool_name}
Description: {tool_record["description"]}
Category: {tool_record["category"]}
Created: {tool_record["created_at"]}
Created by: {tool_record["created_by"]}
Tool ID: {tool_record["tool_id"]}
"""

{tool_record["code"]}
'''
            tool_file.write_text(content)
            logger.debug(f"💾 Tool saved to disk: {tool_file}")

        except Exception as e:
            logger.error(f"Failed to save tool to disk: {e}", exc_info=True)

    def _save_tool_to_dynamodb(self, tool_record: Dict[str, Any]):
        """Save tool to DynamoDB for long-term persistence and sharing"""
        try:
            dynamo = get_dynamo_service()
            if dynamo:
                dynamo.create_dynamic_tool(tool_record)
                logger.info(f"💾 Tool saved to DynamoDB: {tool_record['tool_name']} ({tool_record['tool_id']})")
            else:
                logger.warning("⚠️ DynamoDB not available, skipping DB persistence")
        except Exception as e:
            logger.error(f"Failed to save tool to DynamoDB: {e}", exc_info=True)

    def _update_tool_usage_in_dynamodb(self, tool_id: str):
        """Update tool usage stats in DynamoDB"""
        try:
            dynamo = get_dynamo_service()
            if dynamo:
                dynamo.update_dynamic_tool_usage(tool_id)
        except Exception as e:
            logger.error(f"Failed to update tool usage in DynamoDB: {e}", exc_info=True)

    def load_tools_from_disk(self):
        """Load all tools from storage directory"""
        if not self.storage_dir.exists():
            logger.warning(f"Storage directory does not exist: {self.storage_dir}")
            return

        loaded_count = 0
        for tool_file in self.storage_dir.glob("*.py"):
            try:
                full_content = tool_file.read_text()
                tool_name = tool_file.stem

                # Extract metadata from header docstring
                description = "Dynamic tool"
                category = "general"

                lines = full_content.split('\n')
                for line in lines:
                    if 'Description:' in line:
                        description = line.split('Description:')[1].strip()
                    elif 'Category:' in line:
                        category = line.split('Category:')[1].strip()

                # Extract actual code (skip header docstring)
                # Find the end of the header docstring
                code_start = full_content.find('"""', 10)  # Skip first """
                if code_start != -1:
                    code_start = full_content.find('"""', code_start + 1)  # Find closing """
                    if code_start != -1:
                        code = full_content[code_start + 3:].strip()
                    else:
                        code = full_content
                else:
                    code = full_content

                # Re-register tool (validates and compiles it)
                logger.info(f"📂 Loading tool from disk: {tool_name}")
                result = self.register_tool(
                    tool_name=tool_name,
                    code=code,
                    description=description,
                    category=category,
                    created_by="disk_load"
                )

                if result["success"]:
                    loaded_count += 1
                    logger.info(f"✅ Loaded: {tool_name}")
                else:
                    logger.error(f"❌ Failed to load {tool_name}: {result.get('errors')}")

            except Exception as e:
                logger.error(f"Failed to load tool {tool_file}: {e}", exc_info=True)

        logger.info(f"📦 Loaded {loaded_count} tools from disk")

    def load_tools_from_dynamodb(self):
        """Load all tools from DynamoDB"""
        try:
            dynamo = get_dynamo_service()
            if not dynamo:
                logger.warning("⚠️ DynamoDB not available, skipping DB load")
                return

            tools_from_db = dynamo.list_all_dynamic_tools()
            loaded_count = 0

            for tool_data in tools_from_db:
                try:
                    tool_name = tool_data.get("tool_name")

                    # Skip if already loaded (disk takes precedence)
                    if tool_name in self.tools:
                        logger.debug(f"⏭️ Tool {tool_name} already loaded from disk, skipping DB version")
                        continue

                    code = tool_data.get("code")
                    description = tool_data.get("description", "Dynamic tool")
                    category = tool_data.get("category", "general")

                    logger.info(f"💾 Loading tool from DynamoDB: {tool_name}")
                    result = self.register_tool(
                        tool_name=tool_name,
                        code=code,
                        description=description,
                        category=category,
                        created_by="dynamodb_load"
                    )

                    if result["success"]:
                        # Restore original metadata from DB
                        self.tools[tool_name]["tool_id"] = tool_data.get("tool_id")
                        self.tools[tool_name]["created_at"] = tool_data.get("created_at")
                        self.tools[tool_name]["usage_count"] = tool_data.get("usage_count", 0)
                        self.tools[tool_name]["last_used_at"] = tool_data.get("last_used_at")

                        loaded_count += 1
                        logger.info(f"✅ Loaded from DB: {tool_name}")
                    else:
                        logger.error(f"❌ Failed to load {tool_name} from DB: {result.get('errors')}")

                except Exception as e:
                    logger.error(f"Failed to load tool from DB: {e}", exc_info=True)

            logger.info(f"💾 Loaded {loaded_count} tools from DynamoDB")

        except Exception as e:
            logger.error(f"Failed to load tools from DynamoDB: {e}", exc_info=True)


# Singleton instance
_dynamic_tool_runtime = None


def get_dynamic_tool_runtime() -> DynamicToolRuntime:
    """Get singleton instance of DynamicToolRuntime"""
    global _dynamic_tool_runtime
    if _dynamic_tool_runtime is None:
        _dynamic_tool_runtime = DynamicToolRuntime()

        # Load tools from disk first (local priority)
        try:
            _dynamic_tool_runtime.load_tools_from_disk()
            logger.info(f"📂 Loaded tools from disk")
        except Exception as e:
            logger.warning(f"⚠️ Could not load tools from disk: {e}")

        # Load tools from DynamoDB (shared across Custom AI Diagnostic Models)
        try:
            _dynamic_tool_runtime.load_tools_from_dynamodb()
            logger.info(f"💾 Loaded tools from DynamoDB")
        except Exception as e:
            logger.warning(f"⚠️ Could not load tools from DynamoDB: {e}")

        logger.info(f"✅ Dynamic tool runtime initialized with {len(_dynamic_tool_runtime.tools)} tools")

    return _dynamic_tool_runtime
